apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: grype
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: CLI, syft
    tekton.dev/displayName: syft
    tekton.dev/platforms: "linux/amd64,linux/arm64"    
    #vault.hashicorp.com/agent-inject: "true"
    #vault.hashicorp.com/agent-pre-populate-only: "true"
    #vault.hashicorp.com/agent-inject-token: "true"
    #vault.hashicorp.com/role: "ci-system"
    #vault.hashicorp.com/tls-skip-verify: "true"
spec:
  description: >-
   Task and library for scanning a SBOM and and creating an attestation
  workspaces:
    - name: source-dir
      optional: true
  params:
    - name: GRYPE_ARGS
      description: The Arguments to be passed to Syft command.
      type: array
    - name: COSIGN_SCRIPT
      description: The Arguments to be passed to cosign command.
      type: string      
    - name: GRYPE_IMAGE
      default: docker.io/anchore/grype:v0.56.0
      description: Grype image to be used
      type: string
    - name: COSIGN_IMAGE
      default: quay.io/sallyom/cosign:v2
      description: Cosign image to be used
      type: string      
  steps:
    - name: grype
      image: $(params.GRYPE_IMAGE)
      workingDir: $(workspaces.source-dir.path)
      args:
        - "$(params.GRYPE_ARGS)"
      volumeMounts:
      - name: tmp
        mountPath: /attestation_tmp
      env:
      - name: AWS_ROLE_SESSION_NAME
        value: pipeline-session
      - name: AWS_REGION
        value: us-east-1
      - name: GRYPE_DB_CACHE_DIR
        value: /tmp/.cache             
      #- name: VAULT_ADDR
      #  value: https://vault.vault.svc:8200
      #- name: VAULT_SKIP_VERIFY
      #  value: "true"            
    - name: cosign
      image: $(params.COSIGN_IMAGE)
      command:
        - /bin/bash
      args:
        - -c 
        - "$(params.COSIGN_SCRIPT)"
      env:
      - name: AWS_ROLE_SESSION_NAME
        value: pipeline-session
      - name: AWS_REGION
        value: us-east-1
      - name: DOCKER_CONFIG
        value: /dockerconfig
      #- name: VAULT_ADDR
      #  value: https://vault.vault.svc:8200
      #- name: VAULT_SKIP_VERIFY
      #  value: "true"            
      - name: TUF_URL
        value: https://tuf.apps.open-svc-sts.k1wl.p1.openshiftapps.com
      - name: COSIGN_EXPERIMENTAL
        value: "1"
      volumeMounts:
      - name: tmp
        mountPath: /attestation_tmp        
      - name: dockerconfig
        mountPath: /dockerconfig
        readOnly: true
      securityContext: {}
  volumes:
    - name: tmp
      emptyDir: {}
    - name: dockerconfig
      secret:
        secretName: quay-push