apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  workspaces:
  - name: shared-workspace
  - name: dockerconfig   
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: main
  - name: IMAGE
    type: string
    description: image to be build from the code
  - name: fulcio-url
    type: string
  - name: rekor-url
    type: string
  - name: certificate-identity
    type: string      
  - name: oidc-issuer-url
    type: string      
  results:
    - name: IMAGE_URL
      description: the image url
      value: $(tasks.build-os-image.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: the image digest
      value: $(tasks.build-os-image.results.IMAGE_DIGEST)     
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-os-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: DOCKERFILE
      value: Containerfile
    - name: CONTEXT
      value: coreos-layering/auto-update
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: dockerconfig      
    runAfter:
    - fetch-repository
  - name: create-sbom
    taskRef:
      name: syft
      kind: ClusterTask
    runAfter:
    - build-os-image      
    params:
    - name: SYFT_ARGS
      value: 
      - packages
      - registry:quay.io/sallyom/fedora-coreos-custom@$(tasks.build-os-image.results.IMAGE_DIGEST)
      - -o
      - spdx-json
      - --file
      - /attestation_tmp/attestation.sbom
    - name: BUILDAH_SCRIPT
      value: | 
        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
    - name: COSIGN_SCRIPT
      value: | 
        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        # cosign sign keyless
        # TODO update tekton chains to initialize with BYO tuf
        #cosign sign quay.io/sallyom/fedora-coreos-custom@$(tasks.build-os-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --rekor-url=$(params.rekor-url) --identity-token=$AWS_WEB_IDENTITY_TOKEN_FILE
        # cosign attest keyless flow
        cosign attest quay.io/sallyom/fedora-coreos-custom@$(tasks.build-os-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --rekor-url=$(params.rekor-url) --oidc-issuer=$(params.oidc-issuer-url) --identity-token=$AWS_WEB_IDENTITY_TOKEN_FILE --predicate /attestation_tmp/attestation.sbom --type spdxjson --attachment-tag-prefix sbom-
  - name: create-vulnerability-attestation
    taskRef:
      name: grype
      kind: ClusterTask
    runAfter:
    - create-sbom    
    params:
    - name: GRYPE_ARGS
      value: 
      - registry:quay.io/sallyom/fedora-coreos-custom@$(tasks.build-os-image.results.IMAGE_DIGEST)
      - --file
      - /attestation_tmp/attestation.sarif
      - -o
      - sarif
    - name: COSIGN_SCRIPT
      value: | 
        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        # cosign attest keyless flow
        cosign attest quay.io/sallyom/fedora-coreos-custom@$(tasks.build-os-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --rekor-url=$(params.rekor-url) --oidc-issuer=$(params.oidc-issuer-url) --identity-token=$AWS_WEB_IDENTITY_TOKEN_FILE --predicate /attestation_tmp/attestation.sarif --type https://cosign.sigstore.dev/attestation/vuln/v1 --attachment-tag-prefix sarif-
