apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-run-
spec:
  timeouts:
    pipeline: "0h30m0s"
    finally: "0h30m0s"
  pipelineRef:
    name: build
  params:
  - name: deployment-name
    value: fedora-coreos-custom
  - name: certificate-identity
    value: https://kubernetes.io/namespaces/test-sigstore/serviceaccounts/pipeline 
  - name: git-url
    value: https://github.com/sallyom/edge-imagebuild.git
  - name: IMAGE
    value: quay.io/sallyom/fedora-coreos-custom
  - name: fulcio-url
    value: https://fulcio.apps.open-svc-sts.k1wl.p1.openshiftapps.com
  - name: rekor-url
    value: https://rekor.apps.open-svc-sts.k1wl.p1.openshiftapps.com
  - name: oidc-issuer-url
    value: https://rh-oidc.s3.us-east-1.amazonaws.com/21o4ml1f5kchd6ee9nmh5dhc6efqba38
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: build
  - name: dockerconfig
    secret:
      secretName: quay-push    