apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  workspaces:
  - name: shared-workspace
  - name: dockerconfig   
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: pipelines-1.8
  - name: IMAGE
    type: string
    description: image to be build from the code
  - name: fulcio-url
    type: string
  - name: rekor-url
    type: string
  - name: certificate-identity
    type: string      
  - name: oidc-issuer-url
    type: string      
  results:
    - name: IMAGE_URL
      description: the image url
      value: $(tasks.build-image.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: the image digest
      value: $(tasks.build-image.results.IMAGE_DIGEST)     
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: dockerconfig      
    runAfter:
    - fetch-repository
  - name: create-sbom
    taskRef:
      name: syft
      kind: ClusterTask
    runAfter:
    - build-image      
    params:
    - name: SYFT_ARGS
      value: 
      - packages
      - registry:quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST)
      - -o
      - spdx-json
      - --file
      - /attestation_tmp/attestation.sbom
    - name: COSIGN_SCRIPT
      value: | 
        #cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        export VAULT_TOKEN=$(cat /vault/secrets/token)
        cosign sign quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --rekor-url=$(params.rekor-url) --issue-certificate --key hashivault://ci-system --identity-token=$(cat $AWS_WEB_IDENTITY_TOKEN_FILE) 
        cosign attach sbom --sbom /attestation_tmp/attestation.sbom quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST)
        #cosign attest quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST) --yes --key hashivault://ci-system --predicate /attestation_tmp/attestation.sbom --type spdxjson --attachment-tag-prefix sbom-
        cosign attest quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --key hashivault://ci-system --rekor-url=$(params.rekor-url) --oidc-issuer=$(params.oidc-issuer-url) --identity-token=$(cat $AWS_WEB_IDENTITY_TOKEN_FILE) --predicate /attestation_tmp/attestation.sbom --type spdxjson --attachment-tag-prefix sbom-
  - name: create-vulnerability-attestation
    taskRef:
      name: grype
      kind: ClusterTask
    runAfter:
    - create-sbom    
    params:
    - name: GRYPE_ARGS
      value: 
      - registry:quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST)
      - --file
      - /attestation_tmp/attestation.sarif
      - -o
      - sarif
    - name: COSIGN_SCRIPT
      value: | 
        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        export VAULT_TOKEN=$(cat /vault/secrets/token)
        #cosign attest quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST) --yes --key hashivault://ci-system --predicate /attestation_tmp/attestation.sarif --type vuln --attachment-tag-prefix sarif-
        cosign attest quay.io/sallyom/pipelines-vote-api@$(tasks.build-image.results.IMAGE_DIGEST) --yes --fulcio-url=$(params.fulcio-url) --key hashivault://ci-system --rekor-url=$(params.rekor-url) --oidc-issuer=$(params.oidc-issuer-url) --identity-token=$(cat $AWS_WEB_IDENTITY_TOKEN_FILE) --predicate /attestation_tmp/attestation.sarif --type vuln --attachment-tag-prefix sarif-


