apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: cluster-resources
    app.kubernetes.io/part-of: tekton-pipelines
    operator.tekton.dev/operand-name: tektoncd-chains
  name: tekton-chains-controller-cluster-access-ocp-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-chains-controller-cluster-access-ocp-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-chains-controller
  namespace: openshift-pipelines 
